name: Java CI

on:
  push:
    branches:
      - main
      - phase-1
      - phase-2
      - phase-3

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Java kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Java dosyalarını derle
        run: javac src/oyun/*.java